bcc_quizz_homepage:
    pattern:  /{page}
    defaults: { _controller: bccQuizzBundle:Quizz:index, page: 1 }
    requirements:
        page:  \d*

sdzblog_voir:
    path:      /question/{id}
    defaults:  { _controller: bccQuizzBundle:Quizz:voir }