bcc_quizz_homepage:
    pattern:  /{page}
    defaults: { _controller: bccQuizzBundle:Quizz:index, page: 1 }
    requirements:
        page:  \d*

bcc_quizz_see:
    path:      /question/{id}
    defaults:  { _controller: bccQuizzBundle:Quizz:see }

bcc_quizz_add:
    path:      /add
    defaults:  { _controller: bccQuizzBundle:Quizz:add }

bcc_quizz_modifie:
    path:      /modifie/{id}
    defaults:  { _controller: bccQuizzBundle:Quizz:modifie }
    requirements:
        id:  \d+

bcc_quizz_delete:
    path:      /delete/{id}
    defaults:  { _controller: bccQuizzBundle:Quizz:delete }
    requirements:
        id:  \d+