bcc_quizz_homepage:
    pattern:  /{page}
    defaults: { _controller: bccQuizzBundle:Quizz:index, page: 1 }
    requirements:
        page:  \d*

bcc_quizz_voir:
    path:      /question/{id}
    defaults:  { _controller: bccQuizzBundle:Quizz:see }