<?php

namespace bcc\QuizzBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class QuizzController__JMSInjector
{
    public static function inject($container) {
        $instance = new \bcc\QuizzBundle\Controller\QuizzController();
        return $instance;
    }
}
